### your site title here

title: Faizan Mir


### let's use the minima theme (see https://github.com/jekyll/minima)

theme: minima

minima:
  # date_format: "%b %-d, %Y"
  
# header_pages:
#   - about.md
#   - Portfolio.md

### exclude the instructions / write-up in the README.md

exclude:
- README.md
